# GitHub CI/CD workflow file to push repo to remote server for hosting purposes

name: Push to server

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH keys
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: './'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '~/fyp'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
          port: ${{secrets.REMOTE_PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
          user: ${{secrets.REMOTE_USER}}                                      # Remote server user - REQUIRED true
          #password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
          key: ${{secrets.SSH_REMOTE_KEY}}                                        # Remote server private key - REQUIRED at least one of "password" or "key" 
          pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
          post_upload: echo "This will be executed after the upload!"  # Command to run via ssh after scp upload - REQUIRED false
          ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          scp_options: -v                                              # Flags to use during scp - REQUIRED false - DEFAULT ''