name: Push to server

# GitHub CI/CD workflow file to push repo to remote server for hosting purposes

on:
  workflow_dispatch:

  push:
    branches: [ main, dev ]

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Remove git files
        run: rm -r .git .gitattributes .github .gitignore

      - name: Copy file to remote server
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: "./"
          remote: "~/fyp"
          host: ${{secrets.REMOTE_HOST}}
          user: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SSH_REMOTE_KEY}}
          pre_upload: "sudo chown -R ${{secrets.REMOTE_USER}}:${{secrets.REMOTE_GROUP}} /home/${{secrets.REMOTE_USER}}/fyp"
          post_upload: "cd /home/${{secrets.REMOTE_USER}}/fyp && composer install && sudo chown -R www-data:www-data /home/${{secrets.REMOTE_USER}}/fyp && sudo systemctl reload apache2.service"
          ssh_options: "-o StrictHostKeyChecking=no"
          scp_options: "-v"