name: Push to server

# GitHub CI/CD workflow file to push repo to remote server for hosting purposes

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Display workspace dir
        run: echo "$GITHUB_WORKSPACE"

      - name: Copy file to remote server
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: "$GITHUB_WORKSPACE"
          remote: "~/fyp"
          host: ${{secrets.REMOTE_HOST}}
          user: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SSH_REMOTE_KEY}}
          post_upload: "chown -R ubuntu:ubuntu ."
          #ssh_options: "-o StrictHostKeyChecking=no"
          #scp_options: "-v"