name: Push to server

# GitHub CI/CD workflow file to push repo to remote server for hosting purposes

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Copy file to remote server
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: ${{env.GITHUB_WORKSPACE}}
          remote: "~/fyp"
          host: ${{secrets.REMOTE_HOST}}
          user: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SSH_REMOTE_KEY}}