name: Push to server

# GitHub CI/CD workflow file to push repo to remote server for hosting purposes

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: List dir
        run: echo "$GITHUB_WORKSPACE"

      - name: Copy file to remote server
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: ${{env.GITHUB_WORKSPACE}}
          remote: '~/fyp'
          host: ${{secrets.REMOTE_HOST}}
          port: ${{secrets.REMOTE_PORT}}
          user: ${{secrets.REMOTE_USER}}
          #password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
          key: ${{secrets.SSH_REMOTE_KEY}}
          pre_upload: echo "This will be executed before the upload!"
          post_upload: echo "This will be executed after the upload!"
          ssh_options: -o StrictHostKeyChecking=no
          scp_options: -v